# Generated by Django 3.0.10 on 2021-03-12 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_postulation_comment'),
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='postulation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.Postulation', verbose_name='postulacion'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.Chat', verbose_name='chat'),
        ),
    ]
