# Generated by Django 3.0.10 on 2021-03-12 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_postulation_comment'),
        ('chats', '0002_auto_20210312_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='postulation',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Postulation', verbose_name='postulacion'),
        ),
    ]
