# Generated by Django 3.0.10 on 2021-03-12 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_postulation_chat'),
        ('chats', '0004_remove_chat_postulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='postulation',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Postulation', verbose_name='postulacion'),
        ),
    ]
