# Generated by Django 3.0.10 on 2021-03-12 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_chat_postulation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='postulation',
        ),
    ]
