# Generated by Django 3.0.10 on 2021-03-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creada'),
        ),
    ]
