# Generated by Django 3.0.10 on 2021-03-12 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('chats', '0002_auto_20210312_1510'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postulation',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_postulations', to=settings.AUTH_USER_MODEL, verbose_name='candidato'),
        ),
        migrations.AddField(
            model_name='postulation',
            name='chat',
            field=models.OneToOneField(auto_created=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chats.Chat', verbose_name='chat'),
        ),
        migrations.AddField(
            model_name='postulation',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post', verbose_name='publicacion'),
        ),
        migrations.AddField(
            model_name='postulation',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='posts.PostulationStatus', verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_posts', to=settings.AUTH_USER_MODEL, verbose_name='creada por'),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='posts.Category', verbose_name='categoria'),
        ),
        migrations.AddField(
            model_name='post',
            name='postulations',
            field=models.ManyToManyField(through='posts.Postulation', to=settings.AUTH_USER_MODEL, verbose_name='postulaciones'),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='posts.PostStatus', verbose_name='estado'),
        ),
    ]
