# Generated by Django 3.0.10 on 2021-03-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210310_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulation',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='comentario'),
        ),
    ]
