# Generated by Django 3.0.10 on 2021-03-12 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210312_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulation',
            name='chat',
        ),
    ]
